services:
  api:
    image: isaacaisha/siisi
    depends_on:
      - postgres
    ports: 
      - "80:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # env_file:
    #   - ./.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_DATABASE_URL=${ADMIN_DATABASE_URL}
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PORT=${ADMIN_PORT}
      - ADMIN_DATABASE=${ADMIN_DATABASE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_OAUTH2_SECRET_KEY=${OAUTH2_SECRET_KEY}
      
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${ADMIN_USER}
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      # # To use pgAdmin
      - POSTGRES_DB=
      # # To use Heroku
      # - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: