name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        environment:
            name: dbt-openai-api
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            ADMIN_DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL }}
            ADMIN_HOST: ${{ secrets.ADMIN_HOST }}
            ADMIN_PORT: 5432
            ADMIN_DATABASE: ${{ secrets.ADMIN_DATABASE }}
            ADMIN_USER: ${{ secrets.ADMIN_USER }}
            ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            ADMIN_ALGORITHM: ${{ secrets.ADMIN_ALGORITHM }}
            ADMIN_ACCESS_TOKEN_EXPIRE_MINUTES: 55
            ADMIN_OAUTH2_SECRET_KEY: ${{ secrets.ADMIN_OAUTH2_SECRET_KEY }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.12.0"

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests with pytest
              run: |
                pip install pytest
                pytest
